baseURL = 'http://kazuf3.github.io/portfolio/'
languageCode = 'en-us'
title = 'My Portfolio'
paginate = 5
theme = 'PaperMod'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true
googleAnalytics = 'G-GDVM608WBX'

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "img/icons8-wrench-cloud-32.png"
  favicon16x16 = "img/icons8-wrench-cloud-16.png"
  favicon32x32 = "img/icons8-wrench-cloud-32.png"
  apple_touch_icon = "img/apple-touch-icon.png"
  safari_pinned_tab = "img/icons8-wrench-cloud-32.png"

  [params.label]
  text = "Home"
  icon = "img/apple-touch-icon.png"
  iconHeight = 35
    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to my portfolio"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/kazuf3"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/kazuf3/portfolio/blob/master/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[markup.highlight]
noClasses = false
